:imagesdir: ../assets/images

= Overall Lab Summary

Whether you experienced this lab at Red Hat Summit, or through a Red Hat led onsite enablement, or independently through the Red Hat Developer Sandbox, we hope you have found it engaging and empowering.

This lab covered a lot of territory.  We built it around a use case related to retail sales.  Enabling remote stores to rapidly meet customer needs in modern terms.  Through an _Art of The Possible_ Mantra, It incorporated AI/ML and application development approaches that together provide enterprise solutions from the edge to the cloud.

Really, though, these approaches can be applied to many industries and business scenarios.

Red Hat OpenShift is the industry leading Application Platform that along with RHEL, and Red Hat Application Services provides AI/ML platform capabilities for building and running AI/ML driven applications.  Together these Red Hat capabilities support best of breed approaches with Open Source and 3rd Party tooling.

Hopefully you can pursue some Art of The Possible options within your own organization, leveraging Red Hat capabilities.  We are always ready to go on that journey with you.

{empty} +

= Finished early?

Congratulations on completing this lab. If you have some spare time, keep learning about _Apache Camel_ and _OpenShift_:

* Read the https://developers.redhat.com/products/redhat-build-of-apache-camel/overview[*_Apache Camel_* page in Red Hat Developers,role=resource,window=_blank] to learn more about the capabilities of Apache Camel.

* Find more https://developers.redhat.com/products/redhat-build-of-apache-camel/getting-started[*_Apache Camel_* hands-on tutorials,role=resource,window=_blank] you can try for free in the *Developer Sandbox*.

{empty} +